# Generated by Django 5.2.1 on 2025-10-10 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=100)),
                ('css_class', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['area', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaning.activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Limpieza',
                'verbose_name_plural': 'Logs de Limpieza',
                'ordering': ['-date', '-timestamp'],
                'indexes': [models.Index(fields=['date', 'user'], name='cleaning_cl_date_3c7dc6_idx')],
                'unique_together': {('activity', 'date', 'user')},
            },
        ),
    ]
