# Generated by Django 5.2.1 on 2025-10-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finanza',
            old_name='monto',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='finanza',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='finanza',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='finanza',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='finanza',
            name='titulo',
        ),
        migrations.AddField(
            model_name='finanza',
            name='autoriza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='clave_inmueble',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finanza',
            name='concepto',
            field=models.CharField(default='Desconocido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finanza',
            name='cta_bancaria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='finanza',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='solicita',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finanza',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
