# Generated by Django 5.2.1 on 2026-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_monto_finanza_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanza',
            name='agua',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finanza',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='categoria',
            field=models.CharField(choices=[('Renta', 'Renta'), ('Gas', 'Gas'), ('Agua', 'Agua'), ('Luz', 'Luz'), ('Luz area comun', 'Luz area comun'), ('Internet', 'Internet'), ('Mantenimiento Mayaj', 'Mantenimiento Mayaj'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
        migrations.AddField(
            model_name='finanza',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='fecha_pago_agua',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='fecha_pago_gas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='fecha_pago_luz',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='gas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finanza',
            name='luz',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finanza',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso')], default='Egreso', max_length=20),
        ),
        migrations.AddField(
            model_name='mantenimientos',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
