# Generated by Django 5.2.1 on 2026-05-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_mantenimientos_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanza',
            name='categoria',
            field=models.CharField(choices=[('Renta', 'Renta'), ('Servicios', 'Servicios'), ('Mantenimiento', 'Mantenimiento'), ('Administrativo', 'Administrativo'), ('Internet', 'Internet'), ('Luz area comun', 'Luz area comun'), ('Agua', 'Agua'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
    ]
