# Generated by Django 5.2.1 on 2026-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_finanza_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanza',
            name='categoria',
            field=models.CharField(choices=[('Renta', 'Renta'), ('Gas', 'Gas'), ('Agua', 'Agua'), ('Luz', 'Luz'), ('Mantenimiento', 'Mantenimiento'), ('Administrativo', 'Administrativo'), ('Internet', 'Internet'), ('Luz area comun', 'Luz area comun'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
    ]
