# Generated by Django 5.2.1 on 2026-04-28 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('date_text', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=160)),
                ('concept', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comments', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='csv_analysis.csvupload')),
            ],
            options={
                'ordering': ['upload_id', 'row_number'],
            },
        ),
    ]
